# Generated by Django 5.2.2 on 2025-06-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Введите телеграмм chat-id",
                max_length=50,
                null=True,
                verbose_name="Телеграмм chat-id",
            ),
        ),
    ]
