# Generated by Django 5.2.2 on 2025-06-09 18:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Где выполнять привычку",
                        max_length=50,
                        verbose_name="Место",
                    ),
                ),
                ("time", models.TimeField(verbose_name="Время выполнения")),
                (
                    "action",
                    models.CharField(
                        help_text="Что именно нужно делать",
                        max_length=100,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False, verbose_name="Признак приятной привычки"
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Ежедневно"),
                            (7, "Еженедельно"),
                            (30, "Ежемесячно"),
                        ],
                        default=1,
                        verbose_name="Периодичность (дни)",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Чем себя наградить после выполнения (например, 'кофе', '5 минут соцсетей')",
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Время в секундах (не более 120)",
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="Минимальное время — 1 секунда."
                            ),
                            django.core.validators.MaxValueValidator(
                                120,
                                message="Привычка не должна занимать больше 2 минут (120 сек).",
                            ),
                        ],
                        verbose_name="Время на выполнение (в секундах)",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, verbose_name="Признак публичности"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "linked_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="main_habit",
                        to="tracking_habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Cоздатель привычки",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "привычка",
                "verbose_name_plural": "привычки",
                "ordering": ["-created_at"],
            },
        ),
    ]
