# Generated by Django 5.2.2 on 2025-06-09 19:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking_habits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_completed",
            field=models.DateField(
                blank=True,
                help_text="Когда привычка была выполнена в последний раз",
                null=True,
                verbose_name="Последнее выполнение",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="action",
            field=models.CharField(
                help_text="Конкретное действие, которое нужно выполнить",
                max_length=100,
                verbose_name="Действие",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="duration",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Время на выполнение в секундах",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(120),
                ],
                verbose_name="Длительность",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(
                default=False,
                help_text="Является ли привычка приятной (наградой)",
                verbose_name="Приятная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Видна ли привычка другим пользователям",
                verbose_name="Публичная",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="linked_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Приятная привычка, которая будет наградой",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="main_habit",
                to="tracking_habits.habit",
                verbose_name="Связанная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Ежедневно"), (7, "Еженедельно"), (30, "Ежемесячно")],
                default=1,
                help_text="Как часто выполнять привычку (в днях)",
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Минимум 1 день"
                    ),
                    django.core.validators.MaxValueValidator(
                        30, message="Максимум 30 дней"
                    ),
                ],
                verbose_name="Периодичность",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="place",
            field=models.CharField(
                help_text="Место, где будет выполняться привычка",
                max_length=50,
                verbose_name="Место выполнения",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                help_text="В какое время выполнять привычку",
                verbose_name="Время выполнения",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="user",
            field=models.ForeignKey(
                help_text="Пользователь, создавший привычку",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
